### ISSUE TITLE
Error converting string representations of lists to actual lists

### ISSUE THREAD

**Issue by Jan-t2b-filip** [ChlupacTheBosmer/DetectFlow#10]
Occured after trying to load the db. database into DetectflowID:

ERROR - root -   Error converting string representations of lists to actual lists. Further exceptions possible: 'flower_bboxes'
Traceback (most recent call last):
  File "detectflow\utils\data_processor.py", line 215, in refine_periods
  File "pandas\core\frame.py", line 4102, in __getitem__
  File "pandas\core\indexes\range.py", line 417, in get_loc
KeyError: 'flower_bboxes'

**Comment by Jan-t2b-filip** [comment]
.db file missing visits_ext table!!

**Comment by ChlupacTheBosmer** [comment]
@Jan-t2b-filip Do you know which recording id this happened with? 

The .db file was missing data in the visits table befor loading or after loading and saving?
