### ISSUE TITLE
Error converting time columns

### ISSUE THREAD

**Issue by Jan-t2b-filip** [ChlupacTheBosmer/DetectFlow#11]
ERROR - root -   Error converting time columns. Further exceptions possible: 'start_real_life_time'
Traceback (most recent call last):
  File "detectflow\utils\data_processor.py", line 226, in refine_periods
  File "pandas\core\frame.py", line 4102, in __getitem__
  File "pandas\core\indexes\range.py", line 417, in get_loc
KeyError: 'start_real_life_time'

**Comment by Jan-t2b-filip** [comment]
.db file missing visits_ext table!!

**Comment by ChlupacTheBosmer** [comment]
@Jan-t2b-filip please provide recording_id or .db to replicate the issue.
