### ISSUE TITLE
Error ensuring column data types and calculating visit duration

### ISSUE THREAD

**Issue by Jan-t2b-filip** [ChlupacTheBosmer/DetectFlow#12]
Occured after trying to load the db. database into DetectflowID:

ERROR - root -   Error ensuring column data types and calculating visit duration. Further exceptions possible: Cannot set a DataFrame without columns to the column visit_duration
Traceback (most recent call last):
  File "detectflow\utils\data_processor.py", line 236, in refine_periods
  File "pandas\core\frame.py", line 4301, in __setitem__
  File "pandas\core\frame.py", line 4464, in _set_item_frame_value
ValueError: Cannot set a DataFrame without columns to the column visit_duration

**Comment by Jan-t2b-filip** [comment]
.db file missing visits_ext table!!

**Comment by ChlupacTheBosmer** [comment]
@Jan-t2b-filip Please provide recording_id or .db that this happened with. Advise whether the data in visits table were missing prior or after the error (loading / saving the .db).
