### ISSUE TITLE
Error when running job in Termius

### ISSUE THREAD

**Issue by DominikAnyz** [ChlupacTheBosmer/DetectFlow#5]
07/20/2024 17:13:44 - ERROR - root -   Focus regions could not be extracted: Error: list index out of range
Traceback (most recent call last):
  File "/storage/plzen1/home/dominikanyz/.local/lib/python3.10/site-packages/detectflow/video/video_diagnoser.py", line 293, in get_focus_regions
    focus_regions.append(self.video_file.get_picture_quality(frame_number).focus_regions)
  File "/storage/plzen1/home/dominikanyz/.local/lib/python3.10/site-packages/detectflow/video/video_data.py", line 249, in get_picture_quality
    frame = self.read_video_frame(frame_indices=frame_number, stream=False)[0].get("frame")
IndexError: list index out of range

**Comment by ChlupacTheBosmer** [comment]
Seems like an error of the video file. The error message means that no video frame could be read from the video. The operation should continue, but obviously if the vide ois broken no frame will be extracted for prediciton.

Question is how did that get through dataloader valdiation?

**Comment by DominikAnyz** [comment]
https://ondemand.grid.cesnet.cz/pun/sys/dashboard/files/fs//storage/projects/yolo_group/videos_to_check
